/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ali
 */
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.LinkedList;
import javax.swing.JOptionPane;
public class UpdateEmploye extends javax.swing.JFrame {

    /**
     * Creates new form UpdateEmploye
     */
    public UpdateEmploye() {
        initComponents();
    }
    
    int id;
    public UpdateEmploye(int id) {
        initComponents();
        this.id = id;
         
        //create Link LIst that get the data of all
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        backBbn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tff = new javax.swing.JTextField();
        cmb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Employee management System");

        backBbn.setText("Back");
        backBbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBbnActionPerformed(evt);
            }
        });

        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter:");

        cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "ID", "NAME", "AGE", "GENDER", "DESIGNATION", "SALLARY" }));
        cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(backBbn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tff, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backBbn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(138, 138, 138))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBbnActionPerformed
        // TODO add your handling code here:
        dispose();
        MainWindow mw = new MainWindow();
        mw.setVisible(true);
    }//GEN-LAST:event_backBbnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        //TODO add your handling code here:
        if(cmb.getSelectedIndex()==0){
           JOptionPane.showMessageDialog(UpdateEmploye.this, "Select The field");
           return;
       }
        LinkedList<String> ll= new LinkedList<String>();
        for (int x=1;x< cmb.getItemCount();x++){
            ll.add(cmb.getItemAt(x));
        }
        String s =cmb.getSelectedItem().toString();
        
        //Update employe set Designation = "Director" where id = 2030
        String query="";
        for (String y :ll){
            if (y==s){
                if("ID".equals(s) || "AGE".equals(s) || "SALLARY".equals(s)){
                    int c = Integer.parseInt(tff.getText());
                    
                    try{
                        if("ID".equals(s)){
                            query ="Update employe set id = ? where id=? ";
                        }
                        else if("AGE".equals(s)){
                            query ="Update employe set Age = ? where id=? ";
                        }
                        else{
                            query ="Update employe set Sallary = ? where id=? ";
                        }
                        
                        Connection con = CP.createC();
                        //String query ="Update employe set ? = ? where id=? ";
                        System.out.println(s.toLowerCase() + " " + c + " " );
                        PreparedStatement stmt = con.prepareStatement(query);
                        //stmt.setString(1,s.toLowerCase());
                        stmt.setInt(1,c);
                        stmt.setInt(2,this.id);
                        stmt.executeUpdate();
                        
                        return;
                        
                    }
                    catch(Exception e){     
                    } 
                }
                else{
                    String c = tff.getText();
                    try{
                        if("NAME".equals(s)){
                            query ="Update employe set Name = ? where id=? ";
                        }
                        else if("DESIGNATION".equals(s)){
                            query ="Update employe set Designation = ? where id=? ";
                        }
                        else{
                            query ="Update employe set Gender = ? where id=? ";
                        }
                        Connection con = CP.createC();
                        
                        //String query ="Update employe set ? = ? where id=? ";    
                        //System.out.println(s.toLowerCase() + " " + c + " " );
                        PreparedStatement stmt = con.prepareStatement(query);
                        
                        stmt.setString(1,c);
                        stmt.setInt(2,this.id);
                        
                        stmt.executeUpdate();
                        return;
                        
                    }
                    catch(Exception e){
                        return;
                    }
                    
                }
                
            }
        }
        
        //dispose();
       // MainWindow mw = new MainWindow();
        //mw.setVisible(true);
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_cmbActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
            
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateEmploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateEmploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateEmploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateEmploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateEmploye().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton backBbn;
    private javax.swing.JComboBox<String> cmb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tff;
    // End of variables declaration//GEN-END:variables
}
